package agent

import (
	"fmt"
	"strings"
)

// planBlockRe matches <plan>...</plan> blocks in LLM output.
// var planBlockRe = regexp.MustCompile(`(?s)<plan>(.*?)</plan>`)

// Plan represents a structured execution plan generated by the LLM.
type Plan struct {
	Steps     []PlanStep
	RawPlan   string
	Completed int
}

// PlanStep is a single step in the execution plan.
type PlanStep struct {
	Description string
	Status      string // "pending", "in_progress", "completed", "failed"
}

const planningInstruction = `
## Planning Mode
Before taking any actions, create a brief execution plan wrapped in <plan> tags.
List 3-7 concrete steps you will take to accomplish this task.
After creating the plan, proceed to execute each step.

Example:
<plan>
1. Check service health status
2. Review recent logs for errors
3. Identify root cause
4. Recommend remediation
</plan>

After each major step, briefly note which step you completed.`

// shouldPlan returns true if the user message suggests a complex task.
func shouldPlan(message string) bool {
	if len(message) > 200 {
		return true
	}
	if strings.Count(message, "?") > 1 {
		return true
	}
	if strings.Count(message, ".") > 2 {
		return true
	}
	complexKeywords := []string{
		"investigate", "troubleshoot", "diagnose", "analyze",
		"debug", "fix", "resolve", "deploy", "migrate",
		"set up", "configure", "implement", "create",
		"incident", "outage", "rollback",
	}
	lower := strings.ToLower(message)
	for _, kw := range complexKeywords {
		if strings.Contains(lower, kw) {
			return true
		}
	}
	return false
}

// progressSummary returns a text summary of plan progress.
func (p *Plan) progressSummary() string {
	if p == nil || len(p.Steps) == 0 {
		return ""
	}
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("\n## Plan Progress (%d/%d steps)\n", p.Completed, len(p.Steps)))
	for i, step := range p.Steps {
		marker := "[ ]"
		if i < p.Completed {
			marker = "[x]"
		} else if i == p.Completed {
			marker = "[>]"
		}
		sb.WriteString(fmt.Sprintf("%s %s\n", marker, step.Description))
	}
	return sb.String()
}
